FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.9 \
    python3=3.10.6-1~22.04 \
    python3-pip

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP/

ADD ./app-req.txt req.txt

ENV FLASK_APP main.py
ENV FLASK_RUN_HOST 0.0.0.0

RUN pip3 install -r req.txt && rm req.txt

ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
