FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.9 \
    python3=3.10.6-1~22.04 \
    python3-pip \
    wget=1.21.2-2ubuntu1 \
    xvfb=2:21.1.3-2ubuntu2.9 \
    devscripts=2.22.1ubuntu1 \
    libgtk-3-0=3.24.33-1ubuntu2 \
    libdbus-glib-1-2=0.112-2build1 \
    libasound2=1.2.6.1-1ubuntu1 \
    openssh-server

RUN mkdir /var/run/sshd

RUN sed 's/#PasswordAuthentication yes/PasswordAuthentication no/' -i /etc/ssh/sshd_config \
    && sed 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' -i /etc/ssh/sshd_config

RUN useradd -ms /bin/bash sshuser
RUN echo 'sshuser:password' | chpasswd

RUN wget -O firefox-setup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64" \
    && tar -xvjf firefox-setup.tar.bz2 \
    && ln -s /usr/local/firefox/firefox /usr/bin/firefox

RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux32.tar.gz \
    && tar -xvzf geckodriver* \
    && cp geckodriver /usr/bin/geckodriver

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP/

ADD ./tester-req.txt req.txt
RUN pip3 install -r req.txt && rm req.txt

ADD tests tests

ENTRYPOINT python3 -m http.server 3000
